name: CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  MVN_ARGS: "--settings .github/maven-settings.xml"

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Set Maven version
      run: ./build/setMavenVersion.sh

    - name: Build and test
      run: mvn verify -fae -DskipITs ${{ env.MVN_ARGS }}

  release-and-publish:
    needs: build-test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: ci
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        pip install bump2version
        sudo npm install -g npm@latest || sudo npm install -g npm@9
        sudo npm install -g \
          @semantic-release/changelog \
          @semantic-release/exec \
          @semantic-release/git \
          @semantic-release/github

    - name: Semantic Release and Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        # Run semantic-release
        npx semantic-release
        
        # Store the exit status
        RELEASE_STATUS=$?
        echo "Semantic release exit status: $RELEASE_STATUS"
        
        # Only publish if semantic-release was successful
        if [ $RELEASE_STATUS -eq 0 ]; then
          echo "Semantic release successful, publishing..."
          
          # Set Maven version
          ./build/setMavenVersion.sh
          
          # Publish Javadoc
          mvn clean javadoc:aggregate ${{ env.MVN_ARGS }}
          ./build/publishJavadoc.sh
          
          # Setup signing and publish to Maven Central
          ./build/setupSigning.sh
          mvn deploy ${{ env.MVN_ARGS }} -DskipTests -P central
          
          echo "Publishing completed successfully!"
        else
          echo "Semantic release did not create a new version, skipping publish"
        fi